version: 2 # use CircleCI 2.0

jobs:
    install:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - run: npm ci
    build:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - run: npm run build
    lint:
        docker:
            - image: circleci/node:10.16.3
        steps:
            - run: npm run lint
