version: 2.1
orbs:
    coveralls: coveralls/coveralls@1.0.6
jobs:
    install-build:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - restore_cache:
                  key: modules-cache-{{ checksum "package-lock.json" }}
            - restore_cache:
                  key: h5p-core-cache-{{ checksum "scripts/install.sh" }}
            - run: npm install
            - restore_cache:
                  key: h5p-examples-cache-{{ checksum "test/data/content-type-cache/real-content-types.json" }}
            - run: npm run download:content
            - save_cache:
                  key: modules-cache-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - save_cache:
                  key: h5p-core-cache-{{ checksum "scripts/install.sh" }}
                  paths:
                      - ./h5p
            - save_cache:
                  key: h5p-examples-cache-{{ checksum "test/data/content-type-cache/real-content-types.json" }}
                  paths:
                      - ./test/data/hub-content
            - persist_to_workspace:
                  root: .
                  paths:
                      - node_modules
                      - h5p
                      - test/data/content-type-cache/real-content-types.json
                      - test/data/hub-content
                      - build

    lint:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run lint

    format:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run format:check

    unit-tests:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run test -- --collect-coverage
            - coveralls/upload:
                  parallel: true
                  flag_name: Unit tests

    integration-tests:
        docker:
            - image: circleci/node:10
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run test:integration -- --collect-coverage
            - coveralls/upload:
                  parallel: true
                  flag_name: Integration tests

    e2e-tests:
        docker:
            - image: circleci/node:10-browsers
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run test:e2e

    db-tests:
        docker:
            - image: circleci/node:10
            - image: circleci/mongo:latest
              environment:
                  MONGO_INITDB_ROOT_USERNAME: root
                  MONGO_INITDB_ROOT_PASSWORD: h5pnodejs
            - image: minio/minio
              environment:
                  MINIO_ACCESS_KEY: minioaccesskey
                  MINIO_SECRET_KEY: miniosecret
              command: server /data
        steps:
            - checkout
            - attach_workspace:
                  at: .
            - run: npm run test:db -- --collect-coverage
            - coveralls/upload:
                  parallel: true
                  flag_name: DB tests

    release:
        docker:
            - image: 'circleci/node:10'
        steps:
            - checkout
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            - attach_workspace:
                  at: .
            - coveralls/upload:
                  parallel_finished: true
            - run:
                  name: release
                  command: npm run semantic-release || true

workflows:
    version: 2
    h5p-nodejs-library:
        jobs:
            - install-build
            - lint:
                  requires:
                      - install-build
            - format:
                  requires:
                      - install-build
            - unit-tests:
                  requires:
                      - install-build
            - e2e-tests:
                  requires:
                      - install-build
            - integration-tests:
                  requires:
                      - install-build
            - db-tests:
                  requires:
                      - install-build
            - release:
                  requires:
                      - install-build
                      - lint
                      - format
                      - unit-tests
                      - e2e-tests
                      - integration-tests
                      - db-tests
